-- Supabase Setup Script for Portfolio
-- Paste this into the "SQL Editor" in your Supabase dashboard and click "Run".

-- 1. Create 'settings' table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB
);

-- 2. Create 'users' table (for admin login)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create 'messages' table (for contact form)
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies for 'settings'
-- Allow anonymous users to SELECT (to view the portfolio)
CREATE POLICY "Allow public select on settings" 
ON settings FOR SELECT 
USING (true);

-- Allow updates for service_role or authenticate via API
-- (For simplicity, we'll allow all operations if the API key is present)
-- Allow all operations for now to ensure connectivity
CREATE POLICY "Allow all on settings" 
ON settings FOR ALL 
USING (true) 
WITH CHECK (true);

-- 6. Create Policies for 'messages'
-- Allow public to INSERT (for the contact form)
CREATE POLICY "Allow public insert on messages" 
ON messages FOR INSERT 
WITH CHECK (true);

-- Allow SELECT so the API can read them (Admin Panel)
CREATE POLICY "Allow select on messages" 
ON messages FOR SELECT 
USING (true);

-- Allow DELETE (Admin Panel)
CREATE POLICY "Allow delete on messages" 
ON messages FOR DELETE 
USING (true);

-- 7. Seed Initial Admin User
-- (Replace with your desired credentials if needed)
INSERT INTO users (email, password) 
VALUES ('admin@kaium.com', 'kaium123')
ON CONFLICT (email) DO NOTHING;

-- 8. Seed Default Portfolio Data (Complete Template)
INSERT INTO settings (key, value)
VALUES ('portfolio_data', '{
  "hero": {
    "name": "Abdul Kaium",
    "title": "Computer Science Student",
    "typingTexts": ["Python Enthusiast", "Cyber Security Learner", "Diploma Student"],
    "description": "Currently studying Computer Science & Technology at Daffodil Polytechnic Institute."
  },
  "about": {
    "title": "Crafting Digital Reality with Security In Mind",
    "description": "I am a Computer Science student with a passion for web development and cybersecurity. I love building things that are not only beautiful but also robust and secure.",
    "bio1": "Based in Dhaka, Bangladesh, I am constantly exploring new technologies and security protocols.",
    "bio2": "My goal is to create seamless user experiences while ensuring that the underlying architecture is bulletproof.",
    "experience": "Daffodil Polytechnic Institute",
    "location": "Dhaka, Bangladesh",
    "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2574&auto=format&fit=crop"
  },
  "skills": [
    {
      "id": "1",
      "title": "Frontend",
      "icon": "Palette",
      "skills": ["React", "TypeScript", "Tailwind CSS", "Framer Motion"]
    },
    {
      "id": "2",
      "title": "Backend",
      "icon": "Code2",
      "skills": ["Node.js", "Express", "PostgreSQL", "SQLite"]
    }
  ],
  "projects": [
    {
      "id": "1",
      "title": "E-Commerce Security Audit",
      "desc": "A comprehensive security audit of a modern e-commerce platform.",
      "tags": ["Cybersecurity", "React", "Node.js"],
      "img": "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=2574&auto=format&fit=crop",
      "githubUrl": "https://github.com/kaium10-lab"
    }
  ],
  "socials": [
    { "id": "1", "name": "GitHub", "url": "https://github.com/kaium10-lab", "icon": "Github" },
    { "id": "2", "name": "LinkedIn", "url": "#", "icon": "Linkedin" },
    { "id": "3", "name": "Email", "url": "mailto:admin@kaium.com", "icon": "Mail" }
  ]
}')
-- 9. Create 'uploads' bucket in Supabase Storage
-- Note: This might not work if your user doesn't have permissions,
-- but typically you can run this in the SQL Editor.
INSERT INTO storage.buckets (id, name, public)
VALUES ('uploads', 'uploads', true)
ON CONFLICT (id) DO NOTHING;

-- 10. Set up Storage Policies
-- Allow public access to all files in the 'uploads' bucket
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'uploads' );

-- Allow anyone to upload to the 'uploads' bucket
-- (In production, you might want to restrict this to authenticated users)
CREATE POLICY "Public Insert"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'uploads' );

-- Allow anyone to delete their own files or all (for admin simplicity)
CREATE POLICY "Public Delete"
ON storage.objects FOR DELETE
USING ( bucket_id = 'uploads' );
