-- Supabase Setup Script for Portfolio
-- Paste this into the "SQL Editor" in your Supabase dashboard and click "Run".

-- 1. Create 'settings' table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB
);

-- 2. Create 'users' table (for admin login)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create 'messages' table (for contact form)
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies for 'settings'
-- Allow anonymous users to SELECT (to view the portfolio)
CREATE POLICY "Allow public select on settings" 
ON settings FOR SELECT 
USING (true);

-- Allow updates for service_role or authenticate via API
-- (For simplicity, we'll allow all operations if the API key is present)
CREATE POLICY "Allow all on settings for service_role" 
ON settings ALL 
USING (true) 
WITH CHECK (true);

-- 6. Create Policies for 'messages'
-- Allow public to INSERT (for the contact form)
CREATE POLICY "Allow public insert on messages" 
ON messages FOR INSERT 
WITH CHECK (true);

-- 7. Seed Initial Admin User
-- (Replace with your desired credentials if needed)
INSERT INTO users (email, password) 
VALUES ('admin@kaium.com', 'kaium123')
ON CONFLICT (email) DO NOTHING;

-- 8. Seed Default Portfolio Data
INSERT INTO settings (key, value)
VALUES ('portfolio_data', '{
  "hero": {
    "name": "Abdul Kaium",
    "title": "Computer Science Student",
    "typingTexts": ["Python Enthusiast", "Cyber Security Learner", "Diploma Student"],
    "description": "Currently studying Computer Science & Technology at Daffodil Polytechnic Institute."
  }
}')
ON CONFLICT (key) DO NOTHING;
